### PR TITLE
Updated deps

### PR DESCRIPTION
**Pull request by Honza-Orchesty**

### CODE REVIEW

**Comment by aljazerzen** [comment]
A little late seeing this, but great job - you did quite a lot of work!

I see you added GH action to publish to npm, nice. Is there a reason to include `lib/` in the source tree?

**Comment by JirsaR** [comment]
HI @aljazerzen. I've rebased the branch and removed temporary changes.

**Comment by aljazerzen** [comment]
Thanks! This looks great!

**Comment by JirsaR** [comment]
Thanks for merge. Can you publish it as a new version of package please?

**Comment by aljazerzen** [comment]
Done. 

Sorry, but my attention is not at this project at the moment and if you wish to contribute, you'd be more than welcome! There is quite a few typos in the README I've just seen and I'm sure much more to be expanded, but have to time to invest here.

**Pull request merged**
