### PR TITLE
Fix queries not handling custom ids

### LINKED ISSUE #1: FilterQueries on a custom-id field doesn't work
Hi, I really like this project. In my playing around with it, I have stumbled upon the following issue:

When an entity has a custom-id field, querying that field doesn't work. This is due to the automatic renaming of that field to `_id`. So the logical workaround is to make queries on `_id` instead.

## Example:
Let `User` be defined as such:
```ts
class Person {
    @id name: string;
    something: string;
}
```
When saving a new user (`{name: 'Henk', something: 'Not important'}`)

Then doing the following will not give a result
`userRepository.findOne({name: 'Henk'});`

But this will
`userRepository.findOne({_id: 'Henk'});`

This is confusing and non-obvious. And therefore error-prone. I'm currently working around this with some data duplication:
```ts
class Person {
    @id id: string;
    name: string;
    something: string;
    
    constructor(name: string, something?: string) {
        this.id = name;
        this.name = name;
        this.something = something;
    }
}
```

## Proposed solution:
I think it should be possible for mongodb-typescript to transform queries by renaming id-annotated fields to how it is called in the collection (_id).

### PR DESCRIPTION
**Pull request by yardenshoham**
Closes #1

### CODE REVIEW

**Comment by aljazerzen** [comment]
This could work, but it would result in a lot of problems in specific use cases. MongoDB filter queries are complicated, so this is probably bigger task that you expected.

I have added a new test file that should pass before we can merge this: 3c02d8bdfa9453db3379832935292f0b8808d4be

Also you just left a `console.log` in a function & added a whole new code style (eg. variables at the start of the function)

**Comment by yardenshoham** [comment]
> I have added a new test file that should pass before we can merge this: [3c02d8b](https://github.com/aljazerzen/mongodb-typescript/commit/3c02d8bdfa9453db3379832935292f0b8808d4be)

I think we perceive the use case differently. My PR makes sure you can use a different name for the mongo `_id` field. It will still be an ObjectID, not a string as the following code suggests:

https://github.com/aljazerzen/mongodb-typescript/blob/3c02d8bdfa9453db3379832935292f0b8808d4be/test/custom-id-queries.spec.ts#L15

You won't be able to set this field, just get it. For this purpose, this PR is complete.

> Also you just left a `console.log` in a function & added a whole new code style (eg. variables at the start of the function)

I've added a commit to rectify this: 1c56c391e0b3b8d99b5cd2b056d5e3a87d052122.

**Comment by aljazerzen** [comment]
Well mongodb does support _id being of any type and a common use case is
users setting it to sequential numbers, like AUTO INCREMENT in SQL
databases.

I could also write same use cases for _id being ObjectId, but it is easier
to understand the intention with using strings.

If we implement this query refitting, it must work on all data types of ids.

Also, current implementation breaks all queries containing arrays.

**Comment by yardenshoham** [comment]
Hmm, you're right. I'll close this now, might revisit in the far future. Feel free to continue the discussion.

**Pull request closed without merging**
